/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as FundamentalsRouteImport } from './routes/fundamentals'
import { Route as CoreRouteImport } from './routes/core'
import { Route as AdvanceRouteImport } from './routes/advance'
import { Route as IndexRouteImport } from './routes/index'

const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const FundamentalsRoute = FundamentalsRouteImport.update({
  id: '/fundamentals',
  path: '/fundamentals',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvanceRoute = AdvanceRouteImport.update({
  id: '/advance',
  path: '/advance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advance': typeof AdvanceRoute
  '/core': typeof CoreRoute
  '/fundamentals': typeof FundamentalsRoute
  '/patterns': typeof PatternsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advance': typeof AdvanceRoute
  '/core': typeof CoreRoute
  '/fundamentals': typeof FundamentalsRoute
  '/patterns': typeof PatternsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advance': typeof AdvanceRoute
  '/core': typeof CoreRoute
  '/fundamentals': typeof FundamentalsRoute
  '/patterns': typeof PatternsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advance' | '/core' | '/fundamentals' | '/patterns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advance' | '/core' | '/fundamentals' | '/patterns'
  id: '__root__' | '/' | '/advance' | '/core' | '/fundamentals' | '/patterns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvanceRoute: typeof AdvanceRoute
  CoreRoute: typeof CoreRoute
  FundamentalsRoute: typeof FundamentalsRoute
  PatternsRoute: typeof PatternsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals': {
      id: '/fundamentals'
      path: '/fundamentals'
      fullPath: '/fundamentals'
      preLoaderRoute: typeof FundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advance': {
      id: '/advance'
      path: '/advance'
      fullPath: '/advance'
      preLoaderRoute: typeof AdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvanceRoute: AdvanceRoute,
  CoreRoute: CoreRoute,
  FundamentalsRoute: FundamentalsRoute,
  PatternsRoute: PatternsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
